"Resource/UI/ClassMenu.res"
{
	"class"
	{
		"ControlName"		"CClassMenu"
		"fieldName"		"class"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"600"
		"tall"			"350"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}

	"joinClass"
	{
		"ControlName"		"CLabelTeamColored"
		"fieldName"		"joinClass"
		"xpos"		"76"
		"ypos"		"22"
		"wide"		"450"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"#Cstrike_Join_Class"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"		"MenuTitle"
	}
	
	"ClassInfo"
	{
		"ControlName"		"Panel"
		"fieldName"		"ClassInfo"
		"xpos"			"244"
		"ypos"			"15"
		"wide"			"330"
		"tall"			"330"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
	}

	"police"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"police"
		"xpos"			"76"
		"ypos"			"65"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_civilprotection"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass 0"
	}
	
	"soldier"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"soldier"
		"xpos"			"76"
		"ypos"			"85"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_overwatchsoldier"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass 1"
	}
	
	"shotgunner"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"shotgunner"
		"xpos"			"76"
		"ypos"			"105"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_overwatchshotgunner"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass 2"
	}
	
	"elite"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"elite"
		"xpos"			"76"
		"ypos"			"125"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_overwatchelite"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass 3"
	}
	
	"assassin"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"assassin"
		"xpos"			"76"
		"ypos"			"145"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_assassin"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass 4"
	}
	
	"spectate"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"spectate"
		"xpos"			"76"
		"ypos"			"265"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Spectate"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"spectate"
		"Default"		"1"
	}
	
	"autoselect"
	{
		"ControlName"		"MouseOverPanelButton"
		"fieldName"		"autoselect"
		"xpos"			"76"
		"ypos"			"285"
		"wide"			"148"
		"tall"			"20"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Cstrike_Auto_Select"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"command"		"joinclass -2"
		"Default"		"1"
	}
}
