"classes/police.res"
{
	"classNameLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"classNameLabel"
		"xpos"			"10"
		"ypos"			"18"
		"wide"			"175"
		"tall"			"15"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#anticitizen_class_civilprotection"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"1"
		"font"			"ClassMenuDefault"
		"wrap"			"0"
	}
	
	"classInfo"
	{
		"ControlName"		"RichText"
		"fieldName"		"classInfo"
		"xpos"			"7"
		"ypos"			"200"
		"wide"			"300"
		"tall"			"90"
		"autoResize"		"3"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"maxchars"		"-1"
		"text"			"#anticitizen_class_civilprotection_info"
		"wrap"			"1"
		"textAlignment"		"north-west"
		"font"			"ClassMenuDefaultSmall"
	}
	
	"Icon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"Icon"
		"xpos"			"7"
		"ypos"			"50"
		"wide"			"256"
		"tall"			"256"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"image"			"classmenu/icon_civilprotection"
	}
}